<?php
declare(strict_types=1);

return [
    'citilink' => [
        'id' => 'citilink',
        'name' => 'Ситилинк',
        'kind' => 'retail',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 5,
        'official' => true,
        'badge' => 'Федеральная сеть',
        'search_url_template' => 'https://www.citilink.ru/search/?text={q}',
        'affiliate_template' => 'https://ad.admitad.com/g/citilink/?ulp={url}',
        'rps' => 2,
        'quota_per_day' => 100000,
        'color' => '#FF5000'
    ],
    'regard' => [
        'id' => 'regard',
        'name' => 'Регард',
        'kind' => 'retail',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 5,
        'official' => true,
        'badge' => 'Специализированный ПК',
        'search_url_template' => 'https://www.regard.ru/catalog?search={q}',
        'affiliate_template' => '{url}?utm_source=pricehub',
        'rps' => 2,
        'quota_per_day' => 50000,
        'color' => '#0055A5'
    ],
    'onlinetrade' => [
        'id' => 'onlinetrade',
        'name' => 'ОнлайнТрейд',
        'kind' => 'retail',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 5,
        'official' => true,
        'badge' => 'Гипермаркет',
        'search_url_template' => 'https://www.onlinetrade.ru/sitesearch.html?query={q}',
        'affiliate_template' => '{url}?friend_id=pricehub',
        'rps' => 2,
        'quota_per_day' => 80000,
        'color' => '#1D70B8'
    ],
    'mvideo' => [
        'id' => 'mvideo',
        'name' => 'М.Видео',
        'kind' => 'retail',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 5,
        'official' => true,
        'badge' => 'Федеральная сеть',
        'search_url_template' => 'https://www.mvideo.ru/listing?q={q}',
        'affiliate_template' => 'https://ad.admitad.com/g/mvideo/?ulp={url}',
        'rps' => 1,
        'quota_per_day' => 50000,
        'color' => '#E31E24'
    ],
    'dns' => [
        'id' => 'dns',
        'name' => 'DNS',
        'kind' => 'retail',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 5,
        'official' => true,
        'badge' => 'Сеть магазинов',
        'search_url_template' => 'https://www.dns-shop.ru/search/?q={q}',
        'affiliate_template' => '{url}',
        'rps' => 2,
        'quota_per_day' => 100000,
        'color' => '#EC6608'
    ],
    'ozon' => [
        'id' => 'ozon',
        'name' => 'Ozon',
        'kind' => 'marketplace',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 4,
        'official' => false,
        'badge' => 'Маркетплейс',
        'search_url_template' => 'https://www.ozon.ru/search/?text={q}',
        'affiliate_template' => 'https://ozon.ru/referral/?code=pricehub&url={url}',
        'rps' => 3,
        'quota_per_day' => 150000,
        'color' => '#005BFF'
    ],
    'wildberries' => [
        'id' => 'wildberries',
        'name' => 'Wildberries',
        'kind' => 'marketplace',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 4,
        'official' => false,
        'badge' => 'Маркетплейс',
        'search_url_template' => 'https://www.wildberries.ru/catalog/0/search.aspx?search={q}',
        'affiliate_template' => '{url}',
        'rps' => 3,
        'quota_per_day' => 120000,
        'color' => '#CB11AB'
    ],
    'yandex_market' => [
        'id' => 'yandex_market',
        'name' => 'Яндекс Маркет',
        'kind' => 'marketplace',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 4,
        'official' => false,
        'badge' => 'Маркетплейс',
        'search_url_template' => 'https://market.yandex.ru/search?text={q}',
        'affiliate_template' => 'https://market.yandex.ru/partner/pricehub?url={url}',
        'rps' => 2,
        'quota_per_day' => 100000,
        'color' => '#FC3F1D'
    ],
    'megamarket' => [
        'id' => 'megamarket',
        'name' => 'Мегамаркет',
        'kind' => 'marketplace',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 4,
        'official' => false,
        'badge' => 'СберМаркет / Бонусы',
        'search_url_template' => 'https://megamarket.ru/catalog/?q={q}',
        'affiliate_template' => 'https://ad.admitad.com/g/megamarket/?ulp={url}',
        'rps' => 2,
        'quota_per_day' => 60000,
        'color' => '#7B1FA2'
    ],
    'aliexpress' => [
        'id' => 'aliexpress',
        'name' => 'AliExpress',
        'kind' => 'crossborder',
        'mode' => 'prices',
        'currency' => 'USD',
        'trust_level' => 3,
        'official' => false,
        'badge' => 'Из Китая / Прямая доставка',
        'search_url_template' => 'https://aliexpress.ru/wholesale?SearchText={q}',
        'affiliate_template' => 'https://s.click.aliexpress.com/e/_pricehub?dl_target_url={url}',
        'rps' => 5,
        'quota_per_day' => 50000,
        'color' => '#FF4747'
    ],
    'joom' => [
        'id' => 'joom',
        'name' => 'Joom',
        'kind' => 'crossborder',
        'mode' => 'prices',
        'currency' => 'RUB',
        'trust_level' => 3,
        'official' => false,
        'badge' => 'Трансграничный',
        'search_url_template' => 'https://www.joom.ru/ru/search/{q}',
        'affiliate_template' => '{url}?partner=pricehub',
        'rps' => 2,
        'quota_per_day' => 30000,
        'color' => '#00BFA5'
    ],
    'avito' => [
        'id' => 'avito',
        'name' => 'Авито',
        'kind' => 'classifieds',
        'mode' => 'link_only',
        'currency' => 'RUB',
        'trust_level' => 2,
        'official' => false,
        'badge' => 'Частные / Б/у',
        'search_url_template' => 'https://www.avito.ru/rossiya?q={q}',
        'affiliate_template' => '{url}',
        'rps' => 0,
        'quota_per_day' => 0,
        'color' => '#00AAFF'
    ]
];
